### ISSUE TITLE
getting an error on newest experimental

### ISSUE THREAD

**Issue by hexob** [dissociativity/PKs_Rebalancing#16]
this is the error

https://imgur.com/a/UsifOxh

this is what did it https://github.com/CleverRaven/Cataclysm-DDA/pull/31180

**Comment by hexob** [comment]
thanks in advance :)

**Comment by hexob** [comment]
i found how to fix it

example:
"type": "furniture",
    "id": "f_spike",
    "name": "hooked spike",
    "description": "",
    "symbol": "J",
    "color": "ltgray",
    "move_cost_mod": 1.5,
    "required_str": -1,
    "flags": [ "SHARP", "NO_ITEM", "TRANSPARENT", "MOUNTABLE" ],
    "bash": {
      "str_min": 18,
      "str_max": 60,
      "sound": "smash!",
      "sound_fail": "tyyyng.",
      "items": [ { "item": "spike", "count": [ 0, 2 ] } ]

add a description after name

**Comment by dissociativity** [comment]
fixed!
