### ISSUE TITLE
error message- flare ammo

### ISSUE THREAD

**Issue by Senteth** [dissociativity/PKs_Rebalancing#17]
Kept getting the errors below, tracked the source down to this mod. Did a fresh install of CDDA with up to date mods to make sure it wasn't just due to incompatibilities with old files.

******************

 DEBUG    : warnings for type flaregun:
there is no actual ammo of type signal_flare defined

 
 FUNCTION : void Item_factory::check_definitions() const
 FILE     : src/item_factory.cpp
 LINE     : 1142

******************

 DEBUG    : warnings for type signal_flare:
ammo type  is not known

 
 FUNCTION : void Item_factory::check_definitions() const
 FILE     : src/item_factory.cpp
 LINE     : 1142

******************

 DEBUG    : warnings for type flare_gmod:
there is no actual ammo of type signal_flare defined

 
 FUNCTION : void Item_factory::check_definitions() const
 FILE     : src/item_factory.cpp
 LINE     : 1142

**Comment by Senteth** [comment]
Update: Removing the following portion of PKs_Rebalancing-master\items\ammo.json appears to fix the issue. Default flare ammo is still available after the change.

  {
    "id": "signal_flare_turtle",
    "type": "AMMO",
    "name": "signal flare",
    "description": "A heavy plastic cartridge made for use in flare guns.  It appears to be a modified 12 gauge shotgun shell.",
    "weight": 32,
    "volume": 1,
    "price": 2500,
    "material": [ "plastic", "powder" ],
    "symbol": "=",
    "color": "red",
    "count": 4,
    "stack_size": 20,
    "ammo_type": [ "signal_flare_turtle", "shot" ],
    "casing": "shot_hull",
    "range": 30,
    "damage": 16,
    "dispersion": 200,
    "recoil": 100,
    "drop": "handflare_lit",
    "effects": [ "NEVER_MISFIRES", "NO_EMBED", "RECOVER_10", "ACT_ON_RANGED_HIT" ]
  },

**Comment by Senteth** [comment]
Update: Removing the portion below from PKs_Rebalancing-master\items\ammo.json appears to fix the issue. Default flare ammo is still available after the change.

  {
    "id": "signal_flare",
    "type": "AMMO",
    "name": "signal flare",
    "description": "A heavy plastic cartridge made for use in flare guns.  It appears to be a modified 12 gauge shotgun shell.",
    "weight": 32,
    "volume": 1,
    "price": 2500,
    "material": [ "plastic", "powder" ],
    "symbol": "=",
    "color": "red",
    "count": 4,
    "stack_size": 20,
    "ammo_type": [ "signal_flare", "shot" ],
    "casing": "shot_hull",
    "range": 30,
    "damage": 16,
    "dispersion": 200,
    "recoil": 100,
    "drop": "handflare_lit",
    "effects": [ "NEVER_MISFIRES", "NO_EMBED", "RECOVER_10", "ACT_ON_RANGED_HIT" ]
  },

**Comment by dissociativity** [comment]
thankyou, fixed!
