### ISSUE TITLE
All the Errors

### ISSUE THREAD

**Issue by roaringjohn** [dissociativity/PKs_Rebalancing#19]
Probably related to #18, I am getting _**all the errors**_ independent of other mods and independent of CDDA build with the newest version of PK:
[debug.log](https://github.com/dissociativity/PKs_Rebalancing/files/3347052/debug.log)

As far as I know, these errors **will** cause a CTD if I even tried to start with a new character.

**Comment by dissociativity** [comment]
fixed!
