### ISSUE TITLE
Crash during world load

### ISSUE THREAD

**Issue by Satin181** [dissociativity/PKs_Rebalancing#35]
DEBUG    : Error: data/mods//PKs_Rebalancing-master//pk_start_locations.json: line 3:30: must specify either id or abstract

[
  {
    "type": "start_location",
                             ^
    "ident": "doomlabs",
    "name": "PRM Laboratories",
    "target": "doomlab_lab_open"

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 816

**Comment by Helldrone** [comment]
[10497] Loading save crash to menu. 

![image](https://user-images.githubusercontent.com/49344129/78705129-4e18b800-790d-11ea-9283-f055673d1888.png)

**Comment by dissociativity** [comment]
in theory fixed now

**Comment by sakarax** [comment]
Actually I'm still getting this same exact error...

**Comment by sakarax** [comment]
> Actually I'm still getting this same exact error...

sorry, Line 781:

 DEBUG    : Error: data/mods//PKs_Rebalancing-master//pk_start_locations.json: line 3:30: must specify either id or abstract

[
  {
    "type": "start_location",
                             ^
    "id": "doomlabs",
    "name": "PRM Laboratories",
    "terrain": [ "doomlab_lab_open" ]


 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 781
