### ISSUE TITLE
Crash during world loading 

### ISSUE THREAD

**Issue by OsgardOfAstora** [dissociativity/PKs_Rebalancing#37]
Installed the mod (PK's Rebalancing-master), started the game through the executable, selected the mod for my new game and attempted to generate a new world.
Game crashed on world loading ...

![Annotation 2020-07-29 013113](https://user-images.githubusercontent.com/68945595/88777435-12179600-d13c-11ea-9e6a-0f762a18e0c7.png)

![Annotation 2020-07-29 013145](https://user-images.githubusercontent.com/68945595/88777462-193ea400-d13c-11ea-8f0c-f8c222b09784.png)

![Capture](https://user-images.githubusercontent.com/68945595/88777498-222f7580-d13c-11ea-9d14-e38890227b09.PNG)

Thanks in advance

**Comment by Szara-ManOfHonor** [comment]
For the flesh angel thing, the flesh angel was removed from core. PK's uses a copy from to change and use the flesh angel, so that removal broke the mod. I'll put in a pull request that should fix it.


Here's the original flesh angel data
`  {
    "id": "mon_flesh_angel",
    "type": "MONSTER",
    "name": { "str": "flesh angel" },
    "description": "A tall and slender man lacking skin and any normalcy of countenance.  Wings of muscle curl forth from its back and a third eye dominates the forehead.",
    "default_faction": "cult",
    "bodytype": "angel",
    "species": [ "ZOMBIE" ],
    "diff": 5,
    "volume": "92500 ml",
    "weight": "120 kg",
    "hp": 200,
    "speed": 120,
    "material": [ "flesh" ],
    "symbol": "H",
    "color": "red",
    "aggression": 100,
    "morale": 100,
    "melee_skill": 9,
    "melee_dice": 3,
    "melee_dice_sides": 4,
    "melee_cut": 0,
    "dodge": 2,
    "harvest": "zombie",
    "special_attacks": [ [ "FEAR_PARALYZE", 0 ], { "type": "bite", "cooldown": 5 } ],
    "death_drops": "default_zombie_clothes",
    "death_function": [ "NORMAL" ],
    "flags": [ "SEES", "HEARS", "SMELLS", "WARM", "HARDTOSHOOT", "ATTACKMON", "HUMAN", "POISON", "REVIVES", "FILTHY" ]
  },`

`  {
    "id": "mon_homunculus",
    "type": "MONSTER",
    "name": { "str": "homunculus", "str_pl": "homunculi" },
    "description": "A pale hairless man with an impressive athletic physique.  Its lidless eyes are totally black, and seeping with blood.",
    "default_faction": "cult",
    "bodytype": "human",
    "species": [ "ZOMBIE" ],
    "volume": "62500 ml",
    "weight": "81500 g",
    "hp": 120,
    "speed": 110,
    "material": [ "flesh" ],
    "symbol": "h",
    "color": "white",
    "aggression": 100,
    "morale": 100,
    "melee_skill": 8,
    "melee_dice": 3,
    "melee_dice_sides": 12,
    "melee_cut": 4,
    "dodge": 6,
    "armor_bash": 4,
    "armor_cut": 2,
    "armor_bullet": 2,
    "harvest": "human",
    "death_function": [ "NORMAL" ],
    "flags": [ "SEES", "HEARS", "SMELLS", "WARM", "BASHES", "GROUP_BASH", "HUMAN", "REVIVES", "CLIMBS", "FILTHY" ]
  },`

And the other monster which was removed, in case PK's uses that as well.
Apparently the code entry breaks formatting. Damnit GitHub.

**Comment by ghost** [comment]
> And the other monster which was removed, in case PK's uses that as well.
> Apparently the code entry breaks formatting. Damnit GitHub.

Thanks! I was confused as to why this was happening. So is there a fix for the meantime? Should I just delete the entry for now?
EDIT: Nevermind, I just used the raw data from [your pull](https://github.com/dissociativity/PKs_Rebalancing/blob/6132fd1c60b50021f5e8bafc8107a8ae91f4cc5a/monsters/cult.json)
