### ISSUE TITLE
torch and battletorch broke

### ISSUE THREAD

**Issue by adamkad1** [dissociativity/PKs_Rebalancing#7]
https://i.imgur.com/AFawkpD.png
space
https://i.imgur.com/WaSWikX.png
space
https://i.imgur.com/WL5lsL4.png
crash

**Comment by teapot156** [comment]
Can also confirm this.
https://discourse.cataclysmdda.org/t/pks-rebalancing-unofficial-patch/16060/149?u=vogt156

**Comment by dissociativity** [comment]
testing a fix now

**Comment by dissociativity** [comment]
waiting on confirmed fix

**Comment by adamkad1** [comment]
allright, the game seems to work for me now
